### ISSUE TITLE
Chronicler: Update according to withdrawn certificates

### ISSUE THREAD

**Issue by tnickelsen** [project-origin/chronicler#5]
### Description

If a claimed certificate is withdrawn, the Chronicler must be updated as well.

Story points: 5

```[tasklist]
### Tasks
- [ ] Implement logic for withdrawn certificates so it's removed from the statistics
- [ ] Implement proccess Withdrawn event
- [ ] Implement process Unclaimed event
```
